### PR TITLE
Fix mismatch between expected props expected by Image component and props received via Site Editor

### LINKED ISSUE #289: list-context.image-list Open in a new tab setting not working
**Describe the bug**
After defining a Link in the site-editor and selecting the "Open in a new tab" option, the link does not get a `target=blank` property and opens at the same tab.

**To Reproduce**

1. Go to [acctglobal.myvtex.com/admin/cms/site-editor](acctglobal.myvtex.com/admin/cms/site-editor)
2. Click on the main banner, add a link and select the open in a new tab setting ( https://nimb.ws/3mSHG8 )
3. Go to [acctglobal.myvtex.com](acctglobal.myvtex.com)
4. Click on the image

**Expected behavior**
When clicking at the image, the link should open in a new tab.

**Screenshots**
Video showing the current behaviour: https://nimb.ws/0lu92K

### PR DESCRIPTION
**Pull request by victorhmp**
#### What does this PR do?

There was a mismatch between the Link type defined by `vtex.native-types`
and the one being expected as props by the Image component.

A new `newTab` property was added and is now supported by the component,
this should enable users to correctly configure links to open in new tabs.

#### How to test it?

Go into this [Workspace](https://slotsplayground--storecomponents.myvtex.com/admin/cms/site-editor) and try updating the link attributes in the first ImageList image using the Site Editor.

Screen Shot 2020-05-08 at 16 11 41

The image below is the result of the configuration above

Screen Shot 2020-05-08 at 16 08 18

#### Describe alternatives you've considered, if any. \*

Considered just copying the original type definition from `vtex.native-types` and change the `newTab` property name to `openNewTab`, but that would defeat the purpose of `vtex.native-types`, so I went with this solution :)

#### Notes

This should close https://github.com/vtex-apps/store-discussion/issues/289 .

### CODE REVIEW

File: react/Image.tsx [hunk 1]
```diff
@@ -62,11 +57,13 @@ function Image(props: ImageProps) {
     />
   )
 
+  const shouldOpenLinkInNewTab = link?.newTab ?? link?.openNewTab
```
Comment (klzns) [inline react/Image.tsx:64]: Comment referencing the other comment?

**Review by klzns — CHANGES_REQUESTED** [review]

File: react/Image.tsx [hunk 2]
```diff
@@ -62,11 +57,17 @@ function Image(props: ImageProps) {
...
+   * properties, check the Image type definition at './typings/image.d.ts'.
+   */
+  const shouldOpenLinkInNewTab = link?.newTab ?? link?.openNewTab
+
   return link ? (
     <a
       href={formatIOMessage({ id: link.url, intl })}
       rel={link.noFollow ? 'nofollow' : ''}
-      target={link.openNewTab ? '_blank' : ''}
+      target={shouldOpenLinkInNewTab ? '_blank' : ''}
```
Comment (Klynger) [inline react/Image.tsx]: I don't think you should pass an empty string to target, maybe is better to pass `'_self'` or `undefined`
```suggestion
      target={shouldOpenLinkInNewTab ? '_blank' : undefined}
```

**Review by Klynger — APPROVED** [review]

**Review by iaronaraujo — APPROVED** [review]

**Review by klzns — APPROVED** [review]
